# Generated by Django 5.2.7 on 2025-12-08 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_AO', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=50, unique=True)),
                ('designation_article', models.CharField(max_length=200)),
                ('udm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('code_famille', models.AutoField(primary_key=True, serialize=False)),
                ('designation_famille', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('code_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('designation_Fournisseur', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fichier', models.CharField(choices=[('ISE', 'ISE'), ('DA', 'DA'), ('AO', 'AO'), ('CMD', 'Commande')], max_length=10)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(default=django.utils.timezone.now)),
                ('nb_lignes_traitees', models.IntegerField(default=0)),
                ('nb_erreurs', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('SUCCESS', 'Succès'), ('PARTIAL', 'Partiel'), ('ERROR', 'Erreur')], default='SUCCESS', max_length=20)),
            ],
            options={
                'verbose_name': "Historique d'import",
                'verbose_name_plural': "Historiques d'imports",
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_plant', models.CharField(max_length=50, unique=True)),
                ('designation_plant', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Appartenir_A_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_AO', models.DateField()),
                ('ao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appel_offre2', to='blog.ao')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article2', to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='Cde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Cde', models.CharField(max_length=50, unique=True)),
                ('ao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appel_offre1', to='blog.ao')),
            ],
        ),
        migrations.CreateModel(
            name='DA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_DA', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appel_offre', to='blog.ao')),
            ],
        ),
        migrations.CreateModel(
            name='Appartenir_A_D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_DA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_DA', models.DateField()),
                ('quantite_DA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article1', to='blog.article')),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_achat1', to='blog.da')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.famille'),
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_Cde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_Cde', models.DateField()),
                ('quantite_Cde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article3', to='blog.article')),
                ('cde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='blog.cde')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to='blog.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ISE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ise', models.CharField(max_length=50, unique=True)),
                ('da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demande_achat', to='blog.da')),
            ],
        ),
        migrations.CreateModel(
            name='Appartenir_A_I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_ise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ise', models.DateField()),
                ('quantite_ise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='blog.article')),
                ('ise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ISE', to='blog.ise')),
            ],
        ),
        migrations.CreateModel(
            name='Appartenir_P_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plant')),
            ],
            options={
                'unique_together': {('plant', 'article')},
            },
        ),
    ]
